# Generated by Django 2.1.5 on 2020-10-29 12:43

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_student_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average_score',
            field=models.FloatField(blank=True, null=True, validators=[classroom.models.validate_negative]),
        ),
    ]
